export const LOAD_CATEGORIES = "LOAD_CATEGORIES";
export const LOAD_SUB_CATEGORIES = "LOAD_SUB_CATEGORIES";
export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const LOAD_SHOPS ="LOAD_SHOPS";
export const LOAD_BRANDS ="LOAD_BRANDS";
export const LOAD_USERS ="LOAD_USERS";
export const SET_CURRENT_USER ="SET_CURRENT_USER";




export const IS_LOADING = "IS_LOADING";
